#!/usr/bin/env bash
# This script lists all currently running processes from all users,
# including those without a TTY, displays them in a user-oriented format,
# and shows the process hierarchy visually.

ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,stime=STARTED,time,command --forest
