#!/usr/bin/env bash
# Script that kills the 4-to_infinity_and_beyond process using kill

# Find PIDs of processes named '4-to_infinity_and_beyond' (excluding grep)
pids=$(ps aux | grep './4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

# Kill the process if PID(s) found
if [ -n "$pids" ]; then
    kill $pids
fi
