#!/usr/bin/env bash
# Script to kill the 4-to_infinity_and_beyond process

# Get PIDs of the process
pids=$(ps aux | grep './4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

# Kill all found PIDs
if [ -n "$pids" ]; then
    echo "$pids" | xargs kill
fi#!/usr/bin/env bash
# Script to kill the 4-to_infinity_and_beyond process

# Get PIDs of the process
pids=$(ps aux | grep './4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

# Kill all found PIDs
if [ -n "$pids" ]; then
    echo "$pids" | xargs kill
fi
